name: Bandit Scan (python code)

on:
  pull_request:
    branches:
      - main
      - ci/jy-security-check
    paths:
      - '**.py'

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run bandit
        if: '!cancelled()'
        run: |
          pip install bandit
          bandit . -r -o CI_bandit_report.txt -f txt
        continue-on-error: true

      - name: Read and filter issues
        run: |
          INPUT_FILE="CI_bandit_report.txt"
          OUTPUT_FILE="CI_bandit_report2.txt"
          awk -v RS='--------------------------------------------------' '!/Severity: Low/' "$INPUT_FILE" > "$OUTPUT_FILE"

      - name: Comment with bandit results
        uses: mshick/add-pr-comment@v2.8.2
        if: '!cancelled()'
        with:
          message-path: CI_bandit_report2.txt
          message-id: 10

      - name: Upload artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          name: Bandit vuln report
          path: CI_bandit_report.txt
