name: Docker Scout (image)

on:
  pull_request:
    branches:
      - main
      - ci/jy-security-scan

jobs:
  build-and-scout:
    runs-on:
      labels: ubuntu-latest
    steps:
      - name: Set Swap Space
        uses: actionhippie/swap-space@v1
        with:
          size: 20G

      - name: Check out code
        uses: actions/checkout@v4

      - name: Extract version from pyproject.toml
        id: version
        run: |
          version=$(grep '^version =' pyproject.toml | awk -F '\"' '{print $2}')
          echo "image_version=$version" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and load Docker image
        env:
          IMAGE_VERSION: ${{ env.image_version }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          tags: ghcr.io/cap-dcwiz/dcwiz-app-utils:test-${{ env.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Authenticate to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Docker Scout
        env:
          IMAGE_VERSION: ${{ env.image_version }}
        uses: docker/scout-action@v1
        with:
          command: cves,recommendations
          sarif-file: dockerscout-output.json
          image: ghcr.io/cap-dcwiz/dcwiz-app-utils:test-${{ env.IMAGE_VERSION }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        if: '!cancelled()'
        uses: actions/upload-artifact@v4
        with:
          path: dockerscout-output.json
