name: Lint Checking

on:
  pull_request:
    branches:
      - main
      - ci/jy-security-check

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1